export const productsMock = [
  {
    id: "product-pan",
    name: "Pan",
    category: "Panadería",
    description: "Pan fresco para la merienda.",
    price: 2,
  },
  {
    id: "product-milk",
    name: "Leche",
    category: "Lácteos",
    description: "Leche nutritiva para compartir.",
    price: 3,
  },
  {
    id: "product-apple",
    name: "Manzana",
    category: "Frutas",
    description: "Fruta saludable y fácil de llevar.",
    price: 1,
  },
  {
    id: "product-juice",
    name: "Jugo",
    category: "Bebidas",
    description: "Una opción refrescante para comparar precios.",
    price: 4,
  },
  {
    id: "product-cookies",
    name: "Galletas",
    category: "Snacks",
    description: "Producto distractor para trabajar la toma de decisiones.",
    price: 3,
  },
  {
    id: "product-cheese",
    name: "Queso",
    category: "Lácteos",
    description: "Producto más caro para reforzar presupuesto.",
    price: 5,
  },
  {
    id: "product-banana",
    name: "Plátano",
    category: "Frutas",
    description: "Producto distractor para practicar la búsqueda.",
    price: 2,
  },
  {
    id: "product-carrot",
    name: "Zanahoria",
    category: "Verduras",
    description: "Producto distractor rico en vitaminas.",
    price: 2,
  },
  {
    id: "product-egg",
    name: "Huevos",
    category: "Abarrotes",
    description: "Producto distractor para completar la despensa.",
    price: 4,
  },
  {
    id: "product-chocolate",
    name: "Chocolate",
    category: "Snacks",
    description: "Producto distractor, un gusto ocasional.",
    price: 4,
  },
];
